openapi: '3.0.2'
info:
  title: Hacker News
  version: '1.0'
  description: hola
servers:
  - url: https://hidden-earth-40420.herokuapp.com/
paths:
  /submissions/1.json:
    get:
      responses:
        '200':
          description: OK